services:
  db:
    image: postgres:16-alpine
    container_name: stock_battle_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: stock_battle
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  app:
    image: ghcr.io/rkritik/ai-stock-battle:latest
    container_name: stock_battle_app
    restart: always
    platform: linux/amd64
    ports:
     - "127.0.0.1:8082:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/stock_battle
      STOCK_URL: ${STOCK_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      JOB_KEY: ${JOB_KEY}
    depends_on:
      - db
  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: stock_battle_admin
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
  #    PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
  #  ports:
  #    - "5050:80"
  #  depends_on:
  #    - db

volumes:
  pgdata:
